#!/bin/sh

# CUPANG : CUrl dibikin gamPANG
# ====================
# uses jq ( for json highlighting )
# thanks to beadlist for the guide!
# by padulkemid
# ====================
# HOW TO USE
# ====================
# 1. comment/un-comment functions on the 'script' tag below ( end of file )
# 2. execute this script by running : 
#      chmod +x (name_of_this_script, default is pcl)
#      ./pcl
# ====================

# functions
create_user() {
  curl -X POST \
    -H 'Content-Type: application/json' \
    -d @$1 \
    -v "$URL/register"
}

login_user() {
  curl -X POST \
    -H 'Content-Type: application/json' \
    -d @$1 \
    -v "$URL/login"
}

list(){
  curl -X GET \
    -H 'Content-Type: application/json' \
    -H "token: $TOKEN" \
    -v "$URL/items"
}

get_users(){
  curl -X GET \
    -H 'Content-Type: application/json' \
    -H "token: $TOKEN" \
    -v "$URL/users"
}


list_id() {
  curl -X GET \
    -H 'Content-Type: application/json' \
    -H "token: $TOKEN" \
    -v "$URL/items/$1"
}

create_item() {
  curl -X POST \
    -H 'Content-Type: application/json' \
    -H "token: $TOKEN" \
    -d @$1 \
    -v "$URL/items"
}




# address
# URL="http://localhost:3000"
URL="https://paduljualan.herokuapp.com"
TOKEN=$(login_user user_login_test.json | jq -r .token)

# script
# I used a file called test.json to send the request
# by default, it searches for this
# ====================================================
# login_user user_login.json | jq '.'
# list | jq '.'
# create_item data_test.json | jq '.'
# list_id 2 | jq '.'
get_users | jq '.'
# create_user data_test.json | jq '.'
